### ISSUE TITLE
Problem with rangePickers, when try to destroy the first one

### ISSUE THREAD

**Issue by Rasool65** [AmirkabirDataMiners/ADM-dateTimePicker#11]
سلام خسته نباشید و ممنون از تایم پیکر فوق العاده تون عزیز .... من از کد شما استفاده کردم به این صورت که یک بازه ی زمانی مشخص کردم و حالت زمان پابانی رو قفل شه تا زمانی که حالت آغاز زمانی می بایست پر شود اول ! ولی مشکلی که هست اینه که زمانی که کاربر زمان رو اشتباه وارد میکنه و وقتی میخواد زمان شروع رو تغییر برده نمیتونه چون زمان پابانی قفل هست به نظرم می بایست هر وقت روی زمان شروع کلیک میکنه زمان پایانی فیلدش رو اتوماتیک خالی کنه.. ممنون میشم راهنمایی بفرمایید

**Comment by MeTe-30** [comment]
Salam,
Tnx Rasool, my pleasure.
Correct me if i'm wrong.
You have two directives like this:
```html
<adm-dtp ng-model="date1" full-data="date1_detail" maxdate="{{date2_detail.unix}}"></adm-dtp>
<adm-dtp ng-model="date2" full-data="date2_detail" mindate="{{date1_detail.unix}}" disable="{{!date1}}"></adm-dtp>
```
and when you selecting both dates and destroy first date, second date going to stuck and maxdate son on?
well, it's not a bug, because it's not just about 2 datePicker, you can link together as many datePicker as you want, and they are linking together by value, not by some kind of ids.
So, there is no way to do it automatically. but you can do what you want by destroying second date value `on-change` of first date value:
```html
<adm-dtp ng-model="date1" full-data="date1_detail" maxdate="{{date2_detail.unix}}" on-change=" date2 = '' "></adm-dtp>
```
This code will destroy second datePicker whenever the first datePicker changed.

**Comment by Rasool65** [comment]
Yes , 
Good Job... 
Thank you

**Comment by MeTe-30** [comment]
Your welcome
