### ISSUE TITLE
How do I set minDate using date and time ?

### ISSUE THREAD

**Issue by DheemanS** [AmirkabirDataMiners/ADM-dateTimePicker#56]
If date1 = 2016/12/01 08:00
then date2 can be anything more than  2016/12/01 08:00 but currently it forces us to set 2016/12/02 or more.

**Comment by MeTe-30** [comment]
I don't think so!
Maybe that's because when you set date1 to `2016/12/01 08:00` and open date2, its default time is 00:00 so at the first you open datePicker as `2016/12/01 00:00` is smaller than `2016/12/01 08:00` you cannot select day `1st`.
But if you change the time to `08:01` day `1st` will be reactivated.
